export const types = {
    steel: 'badge text-bg-secondary',
    fire: 'badge text-bg-danger',
    grass :'badge text-bg-success',
    electric: 'badge text-bg-warning',
    water: 'badge text-bg-primary',
    ice: 'badge text-bg-primary',
    ground: 'badge text-bg-success',
    rock :'badge text-bg-success',
    fairy:'badge text-bg-light',
    poison :'badge text-bg-dark',
    bug :'badge text-bg-secondary',
    dragon:'badge text-bg-info',
    psychic:'badge text-bg-info',
    flying:'badge text-bg-light',
    fighting : 'badge text-bg-secondary',
    normal:'badge text-bg-secondary',
}